### ISSUE TITLE
[Tracker] Integration tests coverage

### ISSUE THREAD

**Issue by jorenbroekema** [ing-bank/lion#373]
In the past, integration tests have showed bugs that were not reported, so it would really help to have these in place.

FormatMixin already has a test suite that runs for lots of inputs that use it in one way or another, and is a good example to start. Same goes for InteractionStateMixin.

I want to start using this issue as a tracker for running integration tests for our core mixins against all our components that implement them.

### DelegateMixin
- [ ] Test suite exists
- [ ] Tested on all components that implement them (x/x)

### DisabledMixin
- [ ] Test suite exists
- [ ] Tested on all components that implement them (x/x)

### DisabledWithTabIndexMixin
- [ ] Test suite exists
- [ ] Tested on all components that implement them (x/x)

### FieldCustomMixin
- [ ] Test suite exists
- [ ] Tested on all components that implement them (x/x)

### FocusMixin
- [ ] Test suite exists
- [ ] Tested on all components that implement them (x/x)

### FormatMixin
- [x] Test suite exists
- [ ] Tested on all components that implement them (7/12)

Missing: Checkbox, Radio, Switch, Select, Option

### FormControlMixin
- [ ] Test suite exists
- [ ] Tested on all components that implement them (x/x)

### FormRegisteringMixin
- [ ] Test suite exists
- [ ] Tested on all components that implement them (x/x)

### FormRegistrarMixin
- [ ] Test suite exists
- [ ] Tested on all components that implement them (x/x)

### FormRegistrarPortalMixin
- [ ] Test suite exists
- [ ] Tested on all components that implement them (x/x)

### InteractionStateMixin
- [x] Test suite exists
- [ ] Tested on all components that implement them (4/12)

Missing: Checkbox, Radio, Input email, Input IBAN, Select, Select Rich, Switch, Textarea

### SlotMixin
- [ ] Test suite exists
- [ ] Tested on all components that implement them (x/x)

### UpdateStylesMixin
- [ ] Test suite exists
- [ ] Tested on all components that implement them (x/x)

**Comment by jorenbroekema** [comment]
Probably some Mixins missing, I only looked in core and field package. Didn't include localize/validate yet

**Comment by erikkroes** [comment]
Hi,

We are closing this issue because we're changing the way we handle feature requests. Your issue will get the "votes needed" label, and people can add 👍 reactions to [vote and show interest](https://github.com/ing-bank/lion/issues?q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc). It will be reopened when this feature gets picked up. 

This we way we clearly focus on bugs in our open issues. At the same time we can see what community interest there is for new features.

Thanks!
