### ISSUE TITLE
Lion v1 release tracker

### ISSUE THREAD

**Issue by jorenbroekema** [ing-bank/lion#787]
Breaking, must have
- [ ] Localize breaking change, refactors, message format lite (@tlouisse / thomas )
- [ ] Removal of Ajax package, use Fetch package (open PR) instead (@jorenbroekema )
- [x] Form registrar/registration "hack" removed, use events (fake via sibling command node for IE11) (@daKmoR / thijs)
- [ ] Fix consistency issues in public APIs (@tlouisse )
- [ ] [Popper v2 breaking change](https://github.com/ing-bank/lion/issues/751) (@jorenbroekema / gerjan)
- [x] Remove LionSingleton (in favor of just.. ES Modules) 
- [ ] Change default lion-datepicker to be a dropdown, not modal (check w designers a lot) (@gerjanvangeest )
- [ ] Validator default message generic (at the moment, it's usually wrong..) (@tlouisse ) 

Not breaking but MUST have
- [ ] Types! 
- [ ] General subclasser documentation + semver for subclassers (is breaking a protected method a breaking change?) (@tlouisse )
- [ ] Lion logo & landing page (@daKmoR )

Not breaking but should have
- [ ] lion-combobox/listbox
- [x] Move from lerna to changesets, move to github actions (@jorenbroekema )
- [ ] Move non-webcomponent related packages to a tools folder (@jorenbroekema )
- [ ] Change overlay config while opened (@jorenbroekema )

Finally
- [ ] Release v1 for all packages excluding perhaps individual packages like providence, babel plugin, remark-extend, etc.

**Comment by tlouisse** [comment]
I would suggest to do this one as well: https://github.com/ing-bank/lion/issues/677 (small breaking change)
