### ISSUE TITLE
Extending documentation issues

### ISSUE THREAD

**Issue by MathieuPuech** [ing-bank/lion#858]
Issues to fix

- [x]  providence search in distribution files #850 
- [x]  providence no-dependencies found #851 
- [x]  providence monorepo compatibility
- [x]  providence windows compatibility #883 
- [x]  babel configuration for monorepo

2 examples have been made to validate the extension of documentation:
https://github.com/MathieuPuech/lea
https://github.com/MathieuPuech/lea-tabs

**Comment by MathieuPuech** [comment]
I've started to try the extension of documentation lea and lea-tabs repo. I will finish when issues are done.

**Comment by tlouisse** [comment]
Note to self: for monorepo support, I think the best approach would be:

- check package json for workspace dirs:
```
  "workspaces": [
    "packages/*"
  ],
```
- run providence in the root of the monorepo
- rewrite all output paths that start with './package' to '' => so `./packages/lea-tabs/lea-tabs.js` => `lea-tabs/lea-tabs.js`

**Comment by tlouisse** [comment]
Ran it on Windows (latest `0.6.0` release) and got the correct result. But this was on WSL. @MathieuPuech I assume you run it in the default windows terminal?

**Comment by tlouisse** [comment]
@MathieuPuech 
Running it on regular windows cmd results in the same errors for me: 
- ` error Error when parsing "C:/Users/t_lou/git/lea-tabs/node_modules/@babel/helper-builder-react-jsx-experimental/src/index.js"` : it tries to parse dependencies it shouldn't
- `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

Making it compatible with Windows would mean:
- Check for all (50+) occurrences of node `path.method()`  whether they provide correct windows paths
- Check all dependencies (like glob/anymatch) for compatibility with windows
- make all related npm tasks (scripts in package.json) compatible with Windows (I can't run tests now and that would be needed to confirm all works)

This seems quite a bit more work than expected 😅 

Would it be possible to use WSL for you or are you not on Windows 10?

I think we should only invest in this if it's blocking for you and if we have many users that can't use WSL.
@daKmoR @jorenbroekema what do you think?

**Comment by MathieuPuech** [comment]
I use git bash which is running commands on standard windows command line with a windows node version. WSL is not windows but a linux on windows, that's why it is working.

If the providence package can't work on windows, it needs to be specified so users wanting to use it don't have errors. And maybe we should add windows detection at the beginning to stop users before they have errors.

**Comment by jorenbroekema** [comment]
In my opinion Windows support is a must, as we do for all our packages including node packages. Especially if it's only paths that are problematic, and there's known ways of fixing those. So for me, this is a blocking bug. But I agree with Mathieu that if necessary we can say the package is experimental and doesn't have windows support yet, so at least they can potentially get around the bug by not using windows but WSL/linux/mac instead

**Comment by tlouisse** [comment]
> WSL is not windows but a linux on windows, that's why it is working.
True indeed. But its usage would make the operation system not a blocking factor anymore.

I agree it's nice to have and we can give some better feedback if it's not supported (yet). I will look a bit deeper into the path problems and get a better understanding where the problems lie.

**Comment by MathieuPuech** [comment]
We can just open an issue for the windows support and add in README.md of providence-analytics information about limited support for now linking to the issue.

**Comment by tlouisse** [comment]
Think I'm getting somewhere in the meantime :) This wip branch gives the right output for me: https://github.com/ing-bank/lion/pull/883/files

**Comment by tlouisse** [comment]
@MathieuPuech Providence monorepo comaptibility should be fixed now as well.

When I ran it on your [lea](https://github.com/MathieuPuech/lea) repo, I got:

```json
[
  {
    "name": "LionTabs",
    "variable": {
      "from": "LionTabs",
      "to": "LeaTabs",
      "paths": [
        {
          "from": "./index.js",
          "to": "lea-tabs/index.js".  // <== this used to be "./packages/lea-tabs/index.js" before
... // etc
```

I needed to add this to package.json:

```
  "dependencies": {
    "@lion/tabs": "^0.5.0"
  },
"scripts": {
    "providence:extend": "providence extend-docs -r \"node_modules/@lion/tabs\" --prefix-from lion --prefix-to lea",
```

This functionality is merged to master and should be available next lion release

**Comment by MathieuPuech** [comment]
I confirm the new providence output seems to be good. There is now some work on the babel configuration needed for monorepo

**Comment by tlouisse** [comment]
Ok, could you elaborate on this a bit more @MathieuPuech ? Does it require extra actions from our side?

**Comment by MathieuPuech** [comment]
There is some configuration needed for 'babel-plugin-extend-docs'. It will not be the same as the configuration of singlerepo documented here: https://lion-web-components.netlify.app/?path=/docs/guidelines-extending-documentation--page#replacing-paths--template-tagnames

Doing this will not work:

```
const providenceExtendConfig = require('./packages/tabs/providence-extend-docs-data.json');

const extendDocsConfig = {
  rootPath: path.resolve('.'),
  changes: providenceExtendConfig,
};

module.exports = {
  overrides: [
    {
      test: ['./node_modules/@lion/*/README.md', './node_modules/@lion/*/docs/*.md'],
      plugins: [['babel-plugin-extend-docs', extendDocsConfig]],
    },
  ],
};
```

I suppose it needs the path from the root of the monorepo, here is the error with this naive config:

```
Syntax error: \node_modules\@lion\tabs\R
EADME.md: babel-plugin-extend-docs: Rewriting import from "./index.js" to
 "./src/LeaTabs.js" but we could not find a file at "src/LeaTabs.js"
```

**Comment by tlouisse** [comment]
Thanks a lot for testing this!

Would it help if you add `throwOnNonExistingPathToFiles: false` to `extendDocsConfig`?

**Comment by MathieuPuech** [comment]
I didn't know about this option. I've added it but I still have this error and storybook not showing anything:

```
GET http://localhost:9001/node_modules/@lion/tabs/lea-tabs.js net::ERR_ABORTED 404 (Not Found)
```

Here is the branch I made for now:

https://github.com/MathieuPuech/lea/compare/feat/extendLionDocumentation

**Comment by tlouisse** [comment]
Thanks. I think there are two problems still.

- Running from the root via `"providence:extend": "providence extend-docs -r \"node_modules/@lion/*\" --prefix-from lion --prefix-to lea"` fails, because it checks whether the package is a dep of the root repo (but it is a dep of a monorepo package).
We could add an `skipCheckMatchDependencies` option to providence, then it generates the right output.
- the `all.overrides.md` file makes the path imports fail. If I disable it, it works (note that I manually disabled the check for matching dependencies in `node_modules/providence-analytics` first

**Comment by tlouisse** [comment]
feat(providence-analytics): add option skipCheckMatchCompatibility #1035 has been merged to master.

This allows to run analysis from the monorepo root again.
If you disable all.overrides.md (or at least the conflicting parts) everything should work now 👍

**Comment by MathieuPuech** [comment]
If I disable `all.overrides.md`, it's working yes but it displays the `<lion-tabs>` demos instead of the extended `<lea-tabs>` demos

**Comment by MathieuPuech** [comment]
I tried different ways but I think my issue is about how to override the stories.

With lea-tabs, you need to override all stories since it's not only a tag change (there is more components in lea-tabs: `<lea-tab>`, `<lea-tab-panel>`).

**Comment by tlouisse** [comment]
@MathieuPuech Sorry for the late response. I took some time for it now and made a mr here: https://github.com/MathieuPuech/lea/pull/2

When I open docs, I see that lea-tabs are rendered and imported (and not lion-tabs) 👍 

Ironically enough, I had to revert the Providence version to one that did not contain the monorepo support (apparently adding `./packages/tabs/index.js`.
That's why providence-analytics is hard set to a prev version now.

Can you confirm that this works for you?
If so, I will do a new providence release that leaves the extend-docs output for mono repos unaltered and then you can rely on latest providence again.

**Comment by MathieuPuech** [comment]
This providence version seems to work, I fixed the yarn artifactory issue to deploy it here: https://deploy-preview-2--mathieupuech-lea.netlify.app/?path=/docs/navigation-tabs--main

The lion documentation is displayed but I don't see any lea-tabs rendered, I suppose it needs the override setup to replace tags (and lea-tabs needs maybe a specific override since there is more custom elements in it)

**Comment by tlouisse** [comment]
Hmm, even when you checkout my branch?

Here's what I get when running `yarn start`:
<img width="1065" alt="Screenshot 2020-11-11 at 17 41 20" src="https://user-images.githubusercontent.com/13814138/98839387-c1574f00-2445-11eb-81cc-472b0ee935de.png">

**Comment by MathieuPuech** [comment]
on your branch
![image](https://user-images.githubusercontent.com/9367152/98889768-8d415580-2468-11eb-8791-12a0c36a32b8.png)

**Comment by tlouisse** [comment]
Thanks for trying and fixing the artifactory links, but it should be unrelated I believe. Maybe it's a windows thing (I ran this on a Mac).

What is the output in `providence:extend`? It should be like this:

```
[
  {
    "name": "LionTabs",
    "variable": {
      "from": "LionTabs",
      "to": "LeaTabs",
      "paths": [
        {
          "from": "./index.js",
          "to": "./packages/tabs/index.js"
        },
        {
          "from": "./src/LionTabs.js",
          "to": "./packages/tabs/index.js"
        },
        ... etc
```

If it is like this for you as well, then the problem might be in babel-plugin-extend-docs again, only on Windows

**Comment by MathieuPuech** [comment]
here is the output of the `providence:extend` script:

```json
[
  {
    "name": "LionTabs",
    "variable": {
      "from": "LionTabs",
      "to": "LeaTabs",
      "paths": [
        {
          "from": "./index.js",
          "to": "./packages/tabs/src/LeaTabs.js"
        },
        {
          "from": "./src/LionTabs.js",
          "to": "./packages/tabs/src/LeaTabs.js"
        },
        {
          "from": "@lion/tabs/index.js",
          "to": "./packages/tabs/src/LeaTabs.js"
        },
        {
          "from": "@lion/tabs/src/LionTabs.js",
          "to": "./packages/tabs/src/LeaTabs.js"
        }
      ]
    }
  }
]
```

**Comment by tlouisse** [comment]
It should generate: 

```
[
  {
    "name": "LionTabs",
    "variable": {
      "from": "LionTabs",
      "to": "LeaTabs",
      "paths": [
        {
          "from": "./index.js",
          "to": "./packages/tabs/index.js"
        },
        {
          "from": "./src/LionTabs.js",
          "to": "./packages/tabs/index.js"
        },
        {
          "from": "@lion/tabs/index.js",
          "to": "./packages/tabs/index.js"
        },
        {
          "from": "@lion/tabs/src/LionTabs.js",
          "to": "./packages/tabs/index.js"
        }
      ]
    },
    "tag": {
      "from": "lion-tabs",
      "to": "lea-tabs",
      "paths": [
        {
          "from": "./lion-tabs.js",
          "to": "./packages/tabs/lea-tabs.js"
        },
        {
          "from": "@lion/tabs/lion-tabs.js",
          "to": "./packages/tabs/lea-tabs.js"
        }
      ]
    }
  }
]
```

So it does not generate the tags entry, and the "to" paths are different.
I'll have to spawn it up in Windows soon to see if I can replicate this...

**Comment by jorenbroekema** [comment]
Hey, just updating this issue, I think I fixed the issue for Windows where the tag / CE was not ending up in the output properly. There was actually a test that failed on windows showing this exact problem, and now that's resolved.

@MathieuPuech  perhaps you can verify? I believe that would be the final "bug" then fixed right 😄 ?
